- hosts: all
  remote_user: ansible
  # become: yes
  # become_method: sudo

  tasks:

     #  copy war file to QA server
     - name: Coping war file
       file:
        path: sai
        state: directory
       when: Artifact == 'sai' 

     #  copy war file to QA server
     - name: Coping war file
       file:
        path: venkat
        state: directory
       when: Artifact == 'venkat'
